{% set name = "kvrocks" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apache/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8883a7d05f604098d92cda84128e919dd513540bdd5efb31da69b366e5c7fec1

build:
  number: 0
  skip: True  # [win or osx]

requirements:
  build:
    - python
    - autoconf
    - make
    - cmake
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - openssl 

test:
  commands:
    - kvrocks --version

about:
  home: https://kvrocks.apache.org
  license: Apache-2.0
  license_file: LICENSE 
  license_family: APACHE
  license_url: https://github.com/apache/kvrocks/blob/2.9/LICENSE
  summary: Apache Kvrocks is a distributed key value NoSQL database that uses RocksDB as storage engine and is compatible with Redis protocol

extra:
  recipe-maintainers:
      - mguijarr
